/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dlp;
import javax.swing.*;
import java.awt.*;
import java.io.InputStream;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class user_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form user_dashboard
     */
    public emp user;
    public user_dashboard(emp Emp) {
        user=Emp;
        initComponents();
        this.setResizable(false);
        eidtext.setText(Emp.eid);
        sendfilepannel.setVisible(false);
        keyreqpannel.setVisible(false);
        filesentpannel.setVisible(false);
        filereceivedpannel.setVisible(false);
        actionpannel.setVisible(false);
        downloadpannel.setVisible(false);
        reqactionpannel.setVisible(false);
        editprofilepannel.setVisible(false);
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT eid FROM EMP";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            
            while (resultSet.next()) {
                if(!resultSet.getString("eid").equals(Emp.eid))
                sendfiledropdown.addItem(resultSet.getString("eid"));
            }
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new RoundedPanel(25, new Color(0,102,102));
        jPanel3.setOpaque(false);
        sendfilebox = new RoundedPanel(25, new Color(135,175,175));
        sendfile = new javax.swing.JLabel();
        jPanel8 = new RoundedPanel(25, new Color(135,175,175));
        requestkey = new javax.swing.JLabel();
        jPanel9 = new RoundedPanel(25, new Color(135,175,175));
        filesent = new javax.swing.JLabel();
        jPanel10 = new RoundedPanel(25, new Color(135,175,175));
        filereceived = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eidtext = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        editprofile = new javax.swing.JButton();
        rightpanel = new javax.swing.JPanel();
        editprofilepannel = new RoundedPanel(25, new Color(135,175,175));
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        eidedittext = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mailedittext = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        phoneedittext = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nameedittext = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();
        passeditlable = new javax.swing.JLabel();
        savechange = new javax.swing.JButton();
        changepass = new javax.swing.JButton();
        passedit = new javax.swing.JPasswordField();
        warninglbl = new javax.swing.JLabel();
        keyreqpannel = new RoundedPanel(25, new Color(135,175,175));
        jScrollPane3 = new javax.swing.JScrollPane();
        keyreqtable = new javax.swing.JTable();
        reqactionpannel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        grantkey = new javax.swing.JButton();
        sendfilepannel = new RoundedPanel(25, new Color(135,175,175));
        sendfiledropdown = new javax.swing.JComboBox<>();
        choseeidlabel = new javax.swing.JLabel();
        SendfileNamelabel = new javax.swing.JLabel();
        sendfilenametext = new javax.swing.JLabel();
        Sendfilesubjextlabel = new javax.swing.JLabel();
        sendfilesubjecttext = new javax.swing.JTextField();
        sendfilechoosebutton = new javax.swing.JButton();
        sendfilefiletext = new javax.swing.JTextField();
        sendfilesendbutton = new javax.swing.JButton();
        Sendfilesubjextlabel1 = new javax.swing.JLabel();
        ext = new javax.swing.JLabel();
        Sendfilesubjextlabel2 = new javax.swing.JLabel();
        keylable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filesentpannel = new RoundedPanel(25, new Color(135,175,175));
        jScrollPane1 = new javax.swing.JScrollPane();
        filesenttable = new javax.swing.JTable();
        filereceivedpannel = new RoundedPanel(25, new Color(135,175,175));
        jScrollPane2 = new javax.swing.JScrollPane();
        receivedfiletable = new javax.swing.JTable();
        actionpannel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reqkey = new javax.swing.JButton();
        showkey = new javax.swing.JButton();
        download = new javax.swing.JButton();
        downloadpannel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        finaldownload = new javax.swing.JButton();
        passkeytext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        atmptlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 735));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        sendfilebox.setBackground(new java.awt.Color(0, 102, 102));

        sendfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sendfile.setText("         Send File");
        sendfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sendfileboxLayout = new javax.swing.GroupLayout(sendfilebox);
        sendfilebox.setLayout(sendfileboxLayout);
        sendfileboxLayout.setHorizontalGroup(
            sendfileboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendfileboxLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sendfile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sendfileboxLayout.setVerticalGroup(
            sendfileboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sendfile, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        requestkey.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        requestkey.setText("      Request Key");
        requestkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestkeyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(requestkey, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestkey, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        filesent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filesent.setText("     File Sent By Me");
        filesent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filesentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(filesent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filesent, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        filereceived.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filereceived.setText("     File Received");
        filereceived.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filereceivedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(filereceived, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filereceived, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendfilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(sendfilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(135, 175, 175));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dlp/icons/user-image-with-black-background.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("EID:");

        eidtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eidtext.setText("jLabel3");

        logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        editprofile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editprofile.setForeground(new java.awt.Color(51, 153, 255));
        editprofile.setText("Profile");
        editprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 833, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editprofile)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(eidtext))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editprofile))
                .addGap(8, 8, 8))
        );

        rightpanel.setBackground(new java.awt.Color(255, 255, 255));

        editprofilepannel.setOpaque(false);
        editprofilepannel.setBackground(new java.awt.Color(135, 175, 175));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("EMP Profile");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("EID:");

        eidedittext.setBackground(new java.awt.Color(204, 204, 204));
        eidedittext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eidedittext.setText("jTextField1");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Phone:");

        mailedittext.setBackground(new java.awt.Color(204, 204, 204));
        mailedittext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mailedittext.setText("jTextField1");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Email:");

        phoneedittext.setBackground(new java.awt.Color(204, 204, 204));
        phoneedittext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneedittext.setText("jTextField1");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Name:");

        nameedittext.setBackground(new java.awt.Color(204, 204, 204));
        nameedittext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameedittext.setText("jTextField1");

        editbtn.setForeground(new java.awt.Color(51, 153, 255));
        editbtn.setText("Edit Profile");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        passeditlable.setBackground(new java.awt.Color(255, 255, 255));
        passeditlable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passeditlable.setText("Password:");

        savechange.setBackground(new java.awt.Color(51, 204, 0));
        savechange.setText("Save");
        savechange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangeActionPerformed(evt);
            }
        });

        changepass.setForeground(new java.awt.Color(51, 155, 253));
        changepass.setText("Edit Password");
        changepass.setActionCommand("Edit Password");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });

        passedit.setBackground(new java.awt.Color(204, 204, 204));
        passedit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passedit.setText("Enter Here");

        warninglbl.setText("(Delete and enter new password)");

        javax.swing.GroupLayout editprofilepannelLayout = new javax.swing.GroupLayout(editprofilepannel);
        editprofilepannel.setLayout(editprofilepannelLayout);
        editprofilepannelLayout.setHorizontalGroup(
            editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editprofilepannelLayout.createSequentialGroup()
                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editbtn))
                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editprofilepannelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(passeditlable, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passedit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changepass))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editprofilepannelLayout.createSequentialGroup()
                                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editprofilepannelLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                                        .addComponent(eidedittext, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addGap(107, 107, 107))
                                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                                        .addComponent(phoneedittext, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savechange)
                                    .addGroup(editprofilepannelLayout.createSequentialGroup()
                                        .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameedittext, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                            .addComponent(mailedittext))))
                                .addGap(61, 61, 61)))))
                .addGap(50, 50, 50))
            .addGroup(editprofilepannelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(warninglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editprofilepannelLayout.setVerticalGroup(
            editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editprofilepannelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(editbtn))
                .addGap(73, 73, 73)
                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(eidedittext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameedittext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailedittext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phoneedittext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(editprofilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passeditlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changepass)
                    .addComponent(passedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warninglbl)
                .addGap(75, 75, 75)
                .addComponent(savechange)
                .addGap(39, 39, 39))
        );

        keyreqpannel.setOpaque(false);
        keyreqpannel.setBackground(new java.awt.Color(135, 175, 175));

        keyreqtable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        keyreqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sent To(EID)", "Name", "Subject", "File ID", "Date", "Status", "Action"
            }
        ));
        keyreqtable.setRowHeight(30);
        keyreqtable.setSelectionBackground(new java.awt.Color(51, 204, 255));
        keyreqtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyreqtableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(keyreqtable);

        reqactionpannel.setBackground(new java.awt.Color(255, 255, 255));
        reqactionpannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Action On Selected Row");

        grantkey.setBackground(new java.awt.Color(102, 255, 102));
        grantkey.setText("Grant");
        grantkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantkeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reqactionpannelLayout = new javax.swing.GroupLayout(reqactionpannel);
        reqactionpannel.setLayout(reqactionpannelLayout);
        reqactionpannelLayout.setHorizontalGroup(
            reqactionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqactionpannelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(reqactionpannelLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(grantkey)
                .addGap(14, 205, Short.MAX_VALUE))
        );
        reqactionpannelLayout.setVerticalGroup(
            reqactionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqactionpannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grantkey)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout keyreqpannelLayout = new javax.swing.GroupLayout(keyreqpannel);
        keyreqpannel.setLayout(keyreqpannelLayout);
        keyreqpannelLayout.setHorizontalGroup(
            keyreqpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyreqpannelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(keyreqpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyreqpannelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyreqpannelLayout.createSequentialGroup()
                        .addComponent(reqactionpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        keyreqpannelLayout.setVerticalGroup(
            keyreqpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyreqpannelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reqactionpannel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        sendfilepannel.setOpaque(false);
        sendfilepannel.setBackground(new java.awt.Color(135, 175, 175));

        sendfiledropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendfiledropdownActionPerformed(evt);
            }
        });

        choseeidlabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        choseeidlabel.setText("CHOOSE EID TO SEND THE FILE");

        SendfileNamelabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        SendfileNamelabel.setText("NAME:");

        sendfilenametext.setBackground(new java.awt.Color(255, 255, 255));
        sendfilenametext.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sendfilenametext.setText("USERNAME");
        sendfilenametext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sendfilenametext.setOpaque(true);

        Sendfilesubjextlabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Sendfilesubjextlabel.setText("SUBJECT:");

        sendfilesubjecttext.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sendfilesubjecttext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sendfilechoosebutton.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        sendfilechoosebutton.setText("CHOOSE FILE");
        sendfilechoosebutton.setBorder(null);
        sendfilechoosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendfilechoosebuttonActionPerformed(evt);
            }
        });

        sendfilefiletext.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        sendfilefiletext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sendfilefiletext.setPreferredSize(new java.awt.Dimension(64, 30));

        sendfilesendbutton.setBackground(new java.awt.Color(153, 255, 153));
        sendfilesendbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sendfilesendbutton.setText("SEND");
        sendfilesendbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendfilesendbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendfilesendbuttonActionPerformed(evt);
            }
        });

        Sendfilesubjextlabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Sendfilesubjextlabel1.setText("FILE TYPE:");

        ext.setBackground(new java.awt.Color(255, 255, 255));
        ext.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ext.setText(" ");
        ext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ext.setOpaque(true);

        Sendfilesubjextlabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Sendfilesubjextlabel2.setText("PASS KEY:");

        keylable.setBackground(new java.awt.Color(255, 255, 255));
        keylable.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        keylable.setText(" ");
        keylable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        keylable.setOpaque(true);

        jLabel3.setText("    (Do not share with anyone)");

        javax.swing.GroupLayout sendfilepannelLayout = new javax.swing.GroupLayout(sendfilepannel);
        sendfilepannel.setLayout(sendfilepannelLayout);
        sendfilepannelLayout.setHorizontalGroup(
            sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendfilepannelLayout.createSequentialGroup()
                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sendfilepannelLayout.createSequentialGroup()
                        .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sendfilepannelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choseeidlabel)
                                    .addComponent(SendfileNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sendfilesubjextlabel))
                                .addGap(29, 29, 29)
                                .addComponent(sendfiledropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sendfilepannelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(sendfilechoosebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sendfilefiletext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(sendfilepannelLayout.createSequentialGroup()
                                        .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(sendfilenametext, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(sendfilesubjecttext))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sendfilesubjextlabel1)
                            .addComponent(Sendfilesubjextlabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keylable, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendfilepannelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(sendfilepannelLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(sendfilesendbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sendfilepannelLayout.setVerticalGroup(
            sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendfilepannelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choseeidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendfiledropdown))
                .addGap(10, 10, 10)
                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendfileNamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendfilenametext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sendfilesubjextlabel)
                    .addComponent(sendfilesubjecttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sendfilesubjextlabel2)
                    .addComponent(keylable))
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendfilepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendfilechoosebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendfilefiletext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sendfilesubjextlabel1)
                    .addComponent(ext))
                .addGap(84, 84, 84)
                .addComponent(sendfilesendbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        filesentpannel.setOpaque(false);
        filesentpannel.setBackground(new java.awt.Color(135, 175, 175));

        filesenttable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filesenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sent To(EID)", "Name", "Subject", "File ID", "Date", "Status"
            }
        ));
        filesenttable.setRowHeight(30);
        filesenttable.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jScrollPane1.setViewportView(filesenttable);

        javax.swing.GroupLayout filesentpannelLayout = new javax.swing.GroupLayout(filesentpannel);
        filesentpannel.setLayout(filesentpannelLayout);
        filesentpannelLayout.setHorizontalGroup(
            filesentpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filesentpannelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        filesentpannelLayout.setVerticalGroup(
            filesentpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filesentpannelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        filereceivedpannel.setOpaque(false);
        filereceivedpannel.setBackground(new java.awt.Color(135, 175, 175));

        receivedfiletable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receivedfiletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender(EID)", "Name", "Subject", "File ID", "Date", "Status", "Action"
            }
        ));
        receivedfiletable.setRowHeight(30);
        receivedfiletable.setSelectionBackground(new java.awt.Color(51, 204, 255));
        receivedfiletable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivedfiletableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(receivedfiletable);

        actionpannel.setBackground(new java.awt.Color(255, 255, 255));
        actionpannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Action On Selected Row");

        reqkey.setBackground(new java.awt.Color(255, 102, 102));
        reqkey.setText("Request Key");
        reqkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqkeyActionPerformed(evt);
            }
        });

        showkey.setBackground(new java.awt.Color(153, 153, 153));
        showkey.setText("Show Key");
        showkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showkeyActionPerformed(evt);
            }
        });

        download.setBackground(new java.awt.Color(102, 255, 102));
        download.setText("Download File");
        download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionpannelLayout = new javax.swing.GroupLayout(actionpannel);
        actionpannel.setLayout(actionpannelLayout);
        actionpannelLayout.setHorizontalGroup(
            actionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionpannelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(showkey, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(actionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionpannelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(actionpannelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(download)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(reqkey, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        actionpannelLayout.setVerticalGroup(
            actionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionpannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showkey)
                    .addComponent(download)
                    .addComponent(reqkey))
                .addGap(46, 46, 46))
        );

        downloadpannel.setBackground(new java.awt.Color(255, 255, 255));
        downloadpannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Action On Selected Row");

        finaldownload.setBackground(new java.awt.Color(102, 255, 102));
        finaldownload.setText("Download File");
        finaldownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finaldownloadActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Pass Key:");

        back.setForeground(new java.awt.Color(255, 0, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel7.setText("Attempt left:");

        atmptlabel.setText("jLabel8");

        javax.swing.GroupLayout downloadpannelLayout = new javax.swing.GroupLayout(downloadpannel);
        downloadpannel.setLayout(downloadpannelLayout);
        downloadpannelLayout.setHorizontalGroup(
            downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downloadpannelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(downloadpannelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(166, 166, 166))
                    .addGroup(downloadpannelLayout.createSequentialGroup()
                        .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passkeytext, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(downloadpannelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(back)))
                        .addGap(18, 18, 18)
                        .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(downloadpannelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atmptlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addGroup(downloadpannelLayout.createSequentialGroup()
                                .addComponent(finaldownload)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        downloadpannelLayout.setVerticalGroup(
            downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadpannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passkeytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finaldownload)
                    .addComponent(jLabel6))
                .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(downloadpannelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back))
                    .addGroup(downloadpannelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(downloadpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(atmptlabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout filereceivedpannelLayout = new javax.swing.GroupLayout(filereceivedpannel);
        filereceivedpannel.setLayout(filereceivedpannelLayout);
        filereceivedpannelLayout.setHorizontalGroup(
            filereceivedpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filereceivedpannelLayout.createSequentialGroup()
                .addGroup(filereceivedpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filereceivedpannelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(filereceivedpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actionpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(downloadpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(filereceivedpannelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        filereceivedpannelLayout.setVerticalGroup(
            filereceivedpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filereceivedpannelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actionpannel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout rightpanelLayout = new javax.swing.GroupLayout(rightpanel);
        rightpanel.setLayout(rightpanelLayout);
        rightpanelLayout.setHorizontalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addComponent(sendfilepannel, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(filesentpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 126, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(filereceivedpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 134, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(keyreqpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 126, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(editprofilepannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 133, Short.MAX_VALUE)))
        );
        rightpanelLayout.setVerticalGroup(
            rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightpanelLayout.createSequentialGroup()
                .addComponent(sendfilepannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(filesentpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 270, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(filereceivedpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 209, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(keyreqpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 268, Short.MAX_VALUE)))
            .addGroup(rightpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightpanelLayout.createSequentialGroup()
                    .addComponent(editprofilepannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 289, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 288, Short.MAX_VALUE))
                    .addComponent(rightpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void sendfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendfileMouseClicked
              sendfile.setForeground(new java.awt.Color(255,255,255));
              requestkey.setForeground(new java.awt.Color(0,0,0));
              filesent.setForeground(new java.awt.Color(0,0,0));
              filereceived.setForeground(new java.awt.Color(0,0,0));
              sendfilepannel.setVisible(true);
              keyreqpannel.setVisible(false);
              filesentpannel.setVisible(false);
              filereceivedpannel.setVisible(false);
              editprofilepannel.setVisible(false);
              
    }//GEN-LAST:event_sendfileMouseClicked

    private void requestkeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestkeyMouseClicked
              sendfile.setForeground(new java.awt.Color(0,0,0));
              requestkey.setForeground(new java.awt.Color(255,255,255));
              filesent.setForeground(new java.awt.Color(0,0,0));
              filereceived.setForeground(new java.awt.Color(0,0,0));
              sendfilepannel.setVisible(false);
              keyreqpannel.setVisible(true);
              filesentpannel.setVisible(false);
              filereceivedpannel.setVisible(false);
              editprofilepannel.setVisible(false);
              
              DefaultTableModel tblmodel=(DefaultTableModel)keyreqtable.getModel();
              tblmodel.setRowCount(0);
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT RECEIVER_EID,NAME,SUBJECT,FILEID,DATE,FILETRANSFER.STATUS FROM FILETRANSFER,EMP WHERE FILETRANSFER.RECEIVER_EID=EMP.EID AND FILETRANSFER.SENDER_EID=? AND FILETRANSFER.STATUS=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,eidtext.getText());
            preparedStatement.setString(2,"Requested");
            ResultSet resultSet = preparedStatement.executeQuery();
            
          while (resultSet.next()) {
                    Object[] row = {
                        resultSet.getString("RECEIVER_EID"),
                        resultSet.getString("NAME"),
                        resultSet.getString("SUBJECT"),
                        resultSet.getString("FILEID"),
                        resultSet.getString("DATE"),
                        resultSet.getString("STATUS"),
                        "Click Here"
                        // Add more columns as needed
                    };
                    tblmodel.addRow(row);
                }
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
              
              
    }//GEN-LAST:event_requestkeyMouseClicked

    private void filesentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesentMouseClicked
              sendfile.setForeground(new java.awt.Color(0,0,0));
              requestkey.setForeground(new java.awt.Color(0,0,0));
              filesent.setForeground(new java.awt.Color(255,255,255));
              filereceived.setForeground(new java.awt.Color(0,0,0));
              sendfilepannel.setVisible(false);
              keyreqpannel.setVisible(false);
              filesentpannel.setVisible(true);
              filereceivedpannel.setVisible(false);
              editprofilepannel.setVisible(false);
              DefaultTableModel tblmodel=(DefaultTableModel)filesenttable.getModel();
              tblmodel.setRowCount(0);
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT RECEIVER_EID,NAME,SUBJECT,FILEID,DATE,FILETRANSFER.STATUS FROM FILETRANSFER,EMP WHERE FILETRANSFER.RECEIVER_EID=EMP.EID AND FILETRANSFER.SENDER_EID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,eidtext.getText());
            ResultSet resultSet = preparedStatement.executeQuery();
            
          while (resultSet.next()) {
                    Object[] row = {
                        resultSet.getString("RECEIVER_EID"),
                        resultSet.getString("NAME"),
                        resultSet.getString("SUBJECT"),
                        resultSet.getString("FILEID"),
                        resultSet.getString("DATE"),
                        resultSet.getString("STATUS"),
                        // Add more columns as needed
                    };
                    tblmodel.addRow(row);
                }
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_filesentMouseClicked

    private void filereceivedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filereceivedMouseClicked
              actionpannel.setVisible(false);
              downloadpannel.setVisible(false);
               sendfile.setForeground(new java.awt.Color(0,0,0));
              requestkey.setForeground(new java.awt.Color(0,0,0));
              filesent.setForeground(new java.awt.Color(0,0,0));
              filereceived.setForeground(new java.awt.Color(255,255,255));
              sendfilepannel.setVisible(false);
              keyreqpannel.setVisible(false);
             filesentpannel.setVisible(false);
              filereceivedpannel.setVisible(true);
              actionpannel.setVisible(false);
              editprofilepannel.setVisible(false);
              DefaultTableModel tblmodel=(DefaultTableModel)receivedfiletable.getModel();
              tblmodel.setRowCount(0);
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT SENDER_EID,NAME,SUBJECT,FILEID,DATE,FILETRANSFER.STATUS FROM FILETRANSFER,EMP WHERE FILETRANSFER.SENDER_EID=EMP.EID AND FILETRANSFER.RECEIVER_EID=? AND FILETRANSFER.STATUS!=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,eidtext.getText());
            preparedStatement.setString(2,"Downloaded");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                    Object[] row = {
                        resultSet.getString("SENDER_EID"),
                        resultSet.getString("NAME"),
                        resultSet.getString("SUBJECT"),
                        resultSet.getString("FILEID"),
                        resultSet.getString("DATE"),
                        resultSet.getString("STATUS"),
                        "CLICK HERE"
                        // Add more columns as needed
                    };
                    if(row[5].toString().equals("Sent")){
                        row[5]="Received";
                    }
                    tblmodel.addRow(row);
                }
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
              
    }//GEN-LAST:event_filereceivedMouseClicked

    private void sendfiledropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendfiledropdownActionPerformed
        String selectedValue = (String) sendfiledropdown.getSelectedItem();
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT name FROM EMP where eid=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,selectedValue);
            ResultSet resultSet = preparedStatement.executeQuery();
          
            if (resultSet.next()) {
                sendfilenametext.setText(resultSet.getString("name"));
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
               
    }//GEN-LAST:event_sendfiledropdownActionPerformed

    private void sendfilechoosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendfilechoosebuttonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    java.io.File selectedFile = fileChooser.getSelectedFile();
                    sendfilefiletext.setText(selectedFile.getAbsolutePath());
                    String extn=sendfilefiletext.getText();
                    int lastDotIndex = sendfilefiletext.getText().lastIndexOf('.');
                    ext.setText(sendfilefiletext.getText().substring(lastDotIndex));
                    passkey key=new passkey();
                    int passkey=key.key();
                    keylable.setText(Integer.toString(passkey));
                } else {
                    sendfilefiletext.setText("");
                }
    }//GEN-LAST:event_sendfilechoosebuttonActionPerformed

    private void sendfilesendbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendfilesendbuttonActionPerformed
        String extn=ext.getText();
        String subject=sendfilesubjecttext.getText();
        String address=sendfilefiletext.getText();
        String recvr = (String) sendfiledropdown.getSelectedItem();
        String sender=eidtext.getText();
        if(subject.isEmpty()|| address.isEmpty()){
                 JOptionPane.showMessageDialog(this,"Please Enter all the field","Try again",JOptionPane.ERROR_MESSAGE);
                 return;
             }
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            fileid fl=new fileid();
            int fid=fl.generateRandomNumber();
            String sql = "INSERT INTO filetransfer (sender_eid,receiver_eid,fileid,status,count_status,attempt,date,subject) values (?,?,?,?,3,2,NOW(),?)";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,sender);
            preparedStatement.setString(2,recvr);
            preparedStatement.setInt(3,fid);
            preparedStatement.setString(4,"Sent");
            preparedStatement.setString(5,subject);
            int row = preparedStatement.executeUpdate();
          
            String sql2 = "INSERT INTO filedata (fileid,filedata,passkey,fileextension) values (?,LOAD_FILE(?),?,?)";
            PreparedStatement statement = conn.prepareStatement(sql2);
 
            statement.setInt(1, fid);
            statement.setString(2,address);
            statement.setInt(3,Integer.parseInt(keylable.getText()));
            statement.setString(4,extn);
            int row2 = statement.executeUpdate();
            
            
            if (row>0&&row2>0) {
                JOptionPane.showMessageDialog(user_dashboard.this, "File Sent successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                sendfilesubjecttext.setText("");
                sendfilefiletext.setText("");
                ext.setText(" ");
                keylable.setText(" ");
            }
            else{
                JOptionPane.showMessageDialog(user_dashboard.this,"Connection Error","Try Again",JOptionPane.ERROR_MESSAGE);
            }
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sendfilesendbuttonActionPerformed

    private void receivedfiletableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivedfiletableMouseClicked
        actionpannel.setVisible(true);
        downloadpannel.setVisible(false);
        passkeytext.setText("");
    }//GEN-LAST:event_receivedfiletableMouseClicked

    private void showkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showkeyActionPerformed
       int i=receivedfiletable.getSelectedRow();
       TableModel model=receivedfiletable.getModel();
       String fid=model.getValueAt(i,3).toString();
       String sts=model.getValueAt(i,5).toString();
       if(!sts.equals("Granted")){
           JOptionPane.showMessageDialog(user_dashboard.this, "Wait till sender grant you pass key", "Not Allowed", JOptionPane.ERROR_MESSAGE);
       }else{
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT PASSKEY FROM FILEDATA WHERE FILEID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,fid);
            ResultSet resultSet = preparedStatement.executeQuery();
          
            if (resultSet.next()) {
                String pass=resultSet.getString("passkey");
                JOptionPane.showMessageDialog(user_dashboard.this, "Your pass key is:"+pass, "Success", JOptionPane.INFORMATION_MESSAGE);
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
       } 
    }//GEN-LAST:event_showkeyActionPerformed

    private void reqkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqkeyActionPerformed
       int i=receivedfiletable.getSelectedRow();
       TableModel model=receivedfiletable.getModel();
       String fid=model.getValueAt(i,3).toString();
       String sts=model.getValueAt(i,5).toString();
       if(!sts.equals("Received")){
           JOptionPane.showMessageDialog(user_dashboard.this, "Already Requested", "Not Allowed", JOptionPane.ERROR_MESSAGE);
       }else{
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "UPDATE FILETRANSFER SET STATUS=?,COUNT_STATUS=COUNT_STATUS-1 WHERE FILEID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,"Requested");
            preparedStatement.setString(2,fid);
            int rows = preparedStatement.executeUpdate();
          
            if (rows==1) {
                JOptionPane.showMessageDialog(user_dashboard.this, "Requested", "Success", JOptionPane.INFORMATION_MESSAGE);
                model.setValueAt("Requested", i, 5);
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_reqkeyActionPerformed

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
       String passkey=passkeytext.getText();
       int i=receivedfiletable.getSelectedRow();
       TableModel model=receivedfiletable.getModel();
       String fid=model.getValueAt(i,3).toString();
       String sts=model.getValueAt(i,5).toString();
       String atmpt="";
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT ATTEMPT FROM FILETRANSFER WHERE FILEID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,fid);
            ResultSet resultSet = preparedStatement.executeQuery();
          
            if (resultSet.next()) {
                atmpt=resultSet.getString("ATTEMPT");
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        atmptlabel.setText(atmpt);
        downloadpannel.setVisible(true);
        actionpannel.setVisible(false);
       
    }//GEN-LAST:event_downloadActionPerformed

    private void finaldownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finaldownloadActionPerformed
       String passkey=passkeytext.getText();
       if(passkey.isEmpty()){
           JOptionPane.showMessageDialog(user_dashboard.this, "Enter Pass key", "Error", JOptionPane.ERROR_MESSAGE);
           return;
       }
       int i=receivedfiletable.getSelectedRow();
       TableModel model=receivedfiletable.getModel();
       String sndrid=model.getValueAt(i,0).toString();
       String sndrname=model.getValueAt(i,1).toString();
       String sub=model.getValueAt(i,2).toString();
       String fid=model.getValueAt(i,3).toString();
       String atmpt="";
       String ext="";
       Boolean b1=false;
        final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT ATTEMPT,FILEEXTENSION FROM FILETRANSFER,FILEDATA WHERE FILETRANSFER.FILEID=? AND FILEDATA.FILEID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,fid);
            preparedStatement.setString(2,fid);
            ResultSet resultSet = preparedStatement.executeQuery();
          
            if (resultSet.next()) {
                atmpt=resultSet.getString("ATTEMPT");
                ext=resultSet.getString("FILEEXTENSION");
                if(Integer.parseInt(atmpt)>0){
                    b1=true;
                }else{
                    JOptionPane.showMessageDialog(user_dashboard.this, "No Attempt Left", "Not Allowed", JOptionPane.ERROR_MESSAGE);
                }
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
       if(b1){
        String destinationFilePath = "D:\\DLP output\\"+sndrname+"("+sndrid+")"+"-"+sub+ext;
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "SELECT filedata,passkey FROM filedata WHERE fileid=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,fid);
            ResultSet resultSet = preparedStatement.executeQuery();
          
            if (resultSet.next()) {
               String tempkey=resultSet.getString("passkey");
               if(tempkey.equals(passkey)){
                   InputStream inputStream = resultSet.getBinaryStream("filedata");
                   savefile fl=new savefile();
                   fl.saveBlobToFile(inputStream, destinationFilePath);
                   
                   JOptionPane.showMessageDialog(user_dashboard.this, "File Downloaded Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                   
                   //recude atmpt to 0 ,count-1 and status to download also get back to action pannel
                   
                    String sql1 = "UPDATE FILETRANSFER SET COUNT_STATUS=COUNT_STATUS-1,STATUS=?,ATTEMPT=0 WHERE fileid=?";
                    PreparedStatement preparedStatement1 = conn.prepareStatement(sql1);
                    preparedStatement1.setString(1,"Downloaded");
                    preparedStatement1.setString(2,fid);
                    int rows = preparedStatement1.executeUpdate();
                    if(rows>0){
                        ((DefaultTableModel) model).removeRow(i);
                        passkeytext.setText("");
                        actionpannel.setVisible(false);
                        downloadpannel.setVisible(false);   
                    }
                   
               }else{
                   //recude attemp in database also in frontend
                   JOptionPane.showMessageDialog(user_dashboard.this, "Wrong Pass key", "Error", JOptionPane.ERROR_MESSAGE);
                   String sql1 = "UPDATE FILETRANSFER SET ATTEMPT=ATTEMPT-1 WHERE fileid=?";
                    PreparedStatement preparedStatement1 = conn.prepareStatement(sql1);
                    preparedStatement1.setString(1,fid);
                    int rows = preparedStatement1.executeUpdate();
                    if(rows>0){
                        String temp=atmptlabel.getText();
                        int n=Integer.parseInt(temp);
                                if(n>0){
                                    n--;
                                }
                        atmptlabel.setText(String.valueOf(n));
                    }
               }
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
       }
    }//GEN-LAST:event_finaldownloadActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       downloadpannel.setVisible(false);
       actionpannel.setVisible(true);
       passkeytext.setText("");
    }//GEN-LAST:event_backActionPerformed

    private void grantkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantkeyActionPerformed
       int i=keyreqtable.getSelectedRow();
       TableModel model=keyreqtable.getModel();
       String fid=model.getValueAt(i,3).toString();
       
       final String url = "jdbc:mysql://localhost:3306/dlp";
        final String user = "root";
        final String password = "";
        try {
            Connection conn = DriverManager.getConnection(url, user, password);
            Statement stmt = conn.createStatement();
            String sql = "UPDATE FILETRANSFER SET STATUS=?,COUNT_STATUS=COUNT_STATUS-1 WHERE FILEID=?";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1,"Granted");
            preparedStatement.setString(2,fid);
            int rows=preparedStatement.executeUpdate();
          
            if (rows>0) {
                JOptionPane.showMessageDialog(user_dashboard.this, "Pass Key Granted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                ((DefaultTableModel) model).removeRow(i);
                reqactionpannel.setVisible(false);
            }
           
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_grantkeyActionPerformed

    private void keyreqtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyreqtableMouseClicked
        reqactionpannel.setVisible(true);
    }//GEN-LAST:event_keyreqtableMouseClicked

    private void editprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileActionPerformed
              sendfile.setForeground(new java.awt.Color(0,0,0));
              requestkey.setForeground(new java.awt.Color(0,0,0));
              filesent.setForeground(new java.awt.Color(0,0,0));
              filereceived.setForeground(new java.awt.Color(0,0,0));
        
        
              sendfilepannel.setVisible(false);
              keyreqpannel.setVisible(false);
              filesentpannel.setVisible(false);
              filereceivedpannel.setVisible(false);
              editprofilepannel.setVisible(true);
              savechange.setVisible(false);
              warninglbl.setVisible(false);
              eidedittext.setText(user.eid);
              nameedittext.setText(user.name);
              mailedittext.setText(user.email);
              phoneedittext.setText(user.mobile);
              passedit.setEchoChar('*');
              
              eidedittext.setEditable(false);
              nameedittext.setEditable(false);
              mailedittext.setEditable(false);
              phoneedittext.setEditable(false);
              passedit.setEditable(false);
              
              
              nameedittext.setBackground(new java.awt.Color(204,204,204));
              mailedittext.setBackground(new java.awt.Color(204,204,204));
              phoneedittext.setBackground(new java.awt.Color(204,204,204));
              passedit.setBackground(new java.awt.Color(204,204,204));
              
    }//GEN-LAST:event_editprofileActionPerformed

    private void savechangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangeActionPerformed
        String name=nameedittext.getText();
        String mail=mailedittext.getText();
        String phone=phoneedittext.getText();
        String password=String.valueOf(passedit.getPassword());
        if(name.isEmpty() || mail.isEmpty() || phone.isEmpty() || password.isEmpty()){
                 JOptionPane.showMessageDialog(this,"Please Enter all the field","Try again",JOptionPane.ERROR_MESSAGE);
             }
        
            String url = "jdbc:mysql://localhost:3306/dlp";
            String username = "root";
            String userpassword = "";


            try {
                Connection conn = DriverManager.getConnection(url, username, userpassword);
                Statement stmt = conn.createStatement();
                if(flagchng){
                    String sql = "UPDATE EMP SET NAME=?,email=?,mobile=?,password=? WHERE EID=?";
                    PreparedStatement preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setString(1,name);
                    preparedStatement.setString(2,mail);
                    preparedStatement.setString(3,phone);
                    passwordmanager pm=new passwordmanager();
                    String encoded_pass=pm.encryptPassword(password);
                    preparedStatement.setString(4,encoded_pass);
                    preparedStatement.setString(5,user.eid);
                    int addrows = preparedStatement.executeUpdate();
                    if(addrows>0){
                        JOptionPane.showMessageDialog(this, "Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        passedit.setText("Enter Here");
                        user.name=name;
                        user.email=mail;
                        user.mobile=phone;
                        editprofilepannel.setVisible(false);
                    }  
                }else{
                    String sql = "UPDATE EMP SET NAME=?,email=?,mobile=? WHERE EID=?";
                    PreparedStatement preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setString(1,name);
                    preparedStatement.setString(2,mail);
                    preparedStatement.setString(3,phone);
                    preparedStatement.setString(4,user.eid);
                    int addrows = preparedStatement.executeUpdate();
                    if(addrows>0){
                        JOptionPane.showMessageDialog(this, "Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        user.name=name;
                        user.email=mail;
                        user.mobile=phone;
                        editprofilepannel.setVisible(false);
                    }  
               }
                

                stmt.close();
                conn.close();

            }catch (Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_savechangeActionPerformed
    Boolean flagchng=false; 
    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        passedit.setBackground(new java.awt.Color(255,255,255));
        passedit.setEditable(true);
        savechange.setVisible(true);
        passeditlable.setText("New Password:");
        passedit.setEchoChar((char) 0);
        warninglbl.setVisible(true);
        flagchng=true;
    }//GEN-LAST:event_changepassActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
              nameedittext.setEditable(true);
              mailedittext.setEditable(true);
              phoneedittext.setEditable(true);
              nameedittext.setBackground(new java.awt.Color(255,255,255));
              mailedittext.setBackground(new java.awt.Color(255,255,255));
              phoneedittext.setBackground(new java.awt.Color(255,255,255));
              
              savechange.setVisible(true);
    }//GEN-LAST:event_editbtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SendfileNamelabel;
    private javax.swing.JLabel Sendfilesubjextlabel;
    private javax.swing.JLabel Sendfilesubjextlabel1;
    private javax.swing.JLabel Sendfilesubjextlabel2;
    private javax.swing.JPanel actionpannel;
    private javax.swing.JLabel atmptlabel;
    private javax.swing.JButton back;
    private javax.swing.JButton changepass;
    private javax.swing.JLabel choseeidlabel;
    private javax.swing.JButton download;
    private javax.swing.JPanel downloadpannel;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton editprofile;
    private javax.swing.JPanel editprofilepannel;
    private javax.swing.JTextField eidedittext;
    private javax.swing.JLabel eidtext;
    private javax.swing.JLabel ext;
    private javax.swing.JLabel filereceived;
    private javax.swing.JPanel filereceivedpannel;
    private javax.swing.JLabel filesent;
    private javax.swing.JPanel filesentpannel;
    private javax.swing.JTable filesenttable;
    private javax.swing.JButton finaldownload;
    private javax.swing.JButton grantkey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel keylable;
    private javax.swing.JPanel keyreqpannel;
    private javax.swing.JTable keyreqtable;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mailedittext;
    private javax.swing.JTextField nameedittext;
    private javax.swing.JPasswordField passedit;
    private javax.swing.JLabel passeditlable;
    private javax.swing.JTextField passkeytext;
    private javax.swing.JTextField phoneedittext;
    private javax.swing.JTable receivedfiletable;
    private javax.swing.JPanel reqactionpannel;
    private javax.swing.JButton reqkey;
    private javax.swing.JLabel requestkey;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JButton savechange;
    private javax.swing.JLabel sendfile;
    private javax.swing.JPanel sendfilebox;
    private javax.swing.JButton sendfilechoosebutton;
    private javax.swing.JComboBox<String> sendfiledropdown;
    private javax.swing.JTextField sendfilefiletext;
    private javax.swing.JLabel sendfilenametext;
    private javax.swing.JPanel sendfilepannel;
    private javax.swing.JButton sendfilesendbutton;
    private javax.swing.JTextField sendfilesubjecttext;
    private javax.swing.JButton showkey;
    private javax.swing.JLabel warninglbl;
    // End of variables declaration//GEN-END:variables
}
